services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql


volumes:
  pgdata:

